### ISSUE TITLE
issue with package.json sample in readme

### ISSUE THREAD

**Issue by nobodxbodon** [gasolin/lingascript#16]
Followed steps [here](https://www.npmjs.com/package/lingascript-cn#%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%9D-%E8%80%8C%E9%9D%9E%E5%85%A8%E5%B1%80%E5%AE%89%E8%A3%9D), and `./node_modules/bin/tsc` doesn't work for me. I change it to `./node_modules/lingascript-cn/bin/tsc` to successfully run `npm run compile`. I wonder if this change is indeed necessary or I missed something during the setup? I'll create a draft PR including this.

**Comment by gasolin** [comment]
I think you did the right thing, thanks
